include(../cmake/CPM.cmake)

CPMAddPackage(
    NAME            fastgltf
    GIT_REPOSITORY  https://github.com/spnda/fastgltf.git
    GIT_TAG         2483b87d19a67c91f2bffc386082001d3ea8bc07
    OPTIONS         "FASTGLTF_USE_CUSTOM_SMALLVECTOR OFF"
    OPTIONS         "FASTGLTF_ENABLE_TESTS OFF"
    OPTIONS         "FASTGLTF_ENABLE_EXAMPLES OFF"
    OPTIONS         "FASTGLTF_ENABLE_DOCS OFF"
    OPTIONS         "FASTGLTF_ENABLE_GLTF_RS OFF"
    OPTIONS         "FASTGLTF_ENABLE_ASSIMP OFF"
    OPTIONS         "FASTGLTF_ENABLE_DEPRECATED_EXT ON"
    OPTIONS         "FASTGLTF_DISABLE_CUSTOM_MEMORY_POOL OFF"
    OPTIONS         "FASTGLTF_USE_64BIT_FLOAT OFF"
    OPTIONS         "FASTGLTF_COMPILE_AS_CPP20 OFF"
    OPTIONS         "FASTGLTF_ENABLE_CPP_MODULES OFF"
    OPTIONS         "FASTGLTF_USE_STD_MODULE OFF"
    SYSTEM          TRUE
)
