# KTX changes global variables CMAKE_ARCHIVE_OUTPUT_DIRECTORY, CMAKE_LIBRARY_OUTPUT_DIRECTORY and
# CMAKE_RUNTIME_OUTPUT_DIRECTORY, save them and restore later
set(TEMPORARY_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
set(TEMPORARY_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
set(TEMPORARY_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY})

include(../cmake/CPM.cmake)

CPMAddPackage(
    NAME            ktx
    GIT_REPOSITORY  https://github.com/KhronosGroup/KTX-Software.git
    GIT_TAG         v4.3.2
    GIT_SHALLOW     TRUE
    GIT_PROGRESS    TRUE
    OPTIONS         "KTX_FEATURE_STATIC_LIBRARY ON"
    OPTIONS         "KTX_FEATURE_TESTS OFF"
    OPTIONS         "KTX_FEATURE_KTX1 ON"
    OPTIONS         "KTX_FEATURE_KTX2 ON"
    OPTIONS         "KTX_FEATURE_TOOLS ON"
    OPTIONS         "KTX_FEATURE_VK_UPLOAD OFF"
    OPTIONS         "KTX_FEATURE_GL_UPLOAD OFF"
    SYSTEM          TRUE
)
if(ktx_ADDED)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${TEMPORARY_ARCHIVE_OUTPUT_DIRECTORY})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${TEMPORARY_LIBRARY_OUTPUT_DIRECTORY})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TEMPORARY_RUNTIME_OUTPUT_DIRECTORY})
endif()
